# Generated by Django 5.2.5 on 2025-09-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Darknet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('body_md5', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('detail_parsing', models.JSONField(blank=True, null=True)),
                ('event', models.JSONField(blank=True, null=True)),
                ('industry', models.JSONField(blank=True, null=True)),
                ('is_read', models.TextField(blank=True, null=True)),
                ('msg_author', models.TextField(blank=True, null=True)),
                ('msg_title_cn', models.TextField(blank=True, null=True)),
                ('msg_description', models.TextField(blank=True, null=True)),
                ('msg_release_time', models.DateField(blank=True, null=True)),
                ('org', models.JSONField(blank=True, null=True)),
                ('page_type', models.JSONField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('regions_city', models.TextField(blank=True, null=True)),
                ('regions_country', models.TextField(blank=True, null=True)),
                ('regions_province', models.TextField(blank=True, null=True)),
                ('root_domain', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('status_code', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('timestamp', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('toplv_domain', models.TextField(blank=True, null=True)),
                ('update_time', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('user_id', models.TextField(blank=True, null=True)),
                ('to_new', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('msg_sample_ss', models.JSONField(blank=True, null=True)),
                ('msg_keyword', models.JSONField(blank=True, null=True)),
                ('msg_webpage_ss', models.TextField(blank=True, null=True)),
                ('child_file', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'darknet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=255, null=True)),
                ('chat_name', models.CharField(blank=True, max_length=255, null=True)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('content_text_md5', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.TextField(blank=True, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=255, null=True)),
                ('hot', models.IntegerField(blank=True, null=True)),
                ('identical_msg_num', models.IntegerField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('media_file_url', models.TextField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, max_length=255, null=True)),
                ('message_date', models.DateField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message_time', models.DateTimeField(blank=True, null=True)),
                ('message_time_old_list', models.TextField(blank=True, null=True)),
                ('org', models.TextField(blank=True, null=True)),
                ('regions', models.TextField(blank=True, null=True)),
                ('sender_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_username', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('page_type', models.TextField(blank=True, null=True)),
                ('child_file', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telegram',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParamSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'param_submissions',
                'managed': True,
            },
        ),
    ]
